start_date: '2024-01-01'
end_date: '2024-12-31'
tickers:
  - 1COV.DE
  - ADS.DE
  - ALV.DE
  - BAS.DE
  - BAYN.DE
  - BEI.DE
  - BMW.DE
  - BNR.DE
  - CBK.DE
  - CON.DE
  - DB1.DE
  - DBK.DE
  - DHL.DE
  - DTE.DE
  - DTG.DE
  - ENR.DE
  - EOAN.DE
  - FME.DE
  - FRE.DE
  - HEI.DE
  - HEN3.DE
  - HNR1.DE
  - IFX.DE
  - MBG.DE
  - MRK.DE
  - MTX.DE
  - MUV2.DE
  - P911.DE
  - PAH3.DE
  - QIA.DE
  - RHM.DE
  - RWE.DE
  - SAP.DE
  - SHL.DE
  - SIE.DE
  - SRT3.DE
  - SY1.DE
  - VNA.DE
  - VOW3.DE
  - ZAL.DE
frequencies:
  - minute
  - hour
  - day
date_ranges:
  minute:
    start_date: '2024-10-02'
    end_date: '2024-12-31'
  hour:
    start_date: '2022-12-31'
    end_date: '2024-12-31'
  day:
    start_date: '2014-12-31'
    end_date: '2024-12-31'
