lightgbm:
  num_leaves: [31, 127]
  max_depth: [-1, 15]
  learning_rate: [0.005, 0.2]
  n_estimators: [300, 1500]
catboost:
  depth: [4, 10]
  l2_leaf_reg: [1, 9]
  bagging_temperature: [0, 1]
tabnet:
  n_d: [16, 64]
  n_steps: [3, 7]
  gamma: [1, 2]
  mask_type: [entmax, sparsemax]
prophet:
  changepoint_prior_scale: [0.01]
  seasonality_prior_scale: [5.0]
n_linear:
  kernel_size: [3, 11]
  num_blocks: [1, 4]
lstm:
  layers: [1, 3]
  hidden: [64, 256]
  dropout: [0.0, 0.3]
tft:
  lr: [0.001]
  hidden: [32]
  epochs: [3]
autoformer:
  seq_len: [96, 192]
  label_len: [48, 96]
  d_model: [256, 512]
informer:
  prob_sparse_k: [5, 10]
  n_heads: [4, 8]
patchtst:
  patch_len: [16, 64]
  d_model: [128, 512]
timesnet:
  scale_factor: [1, 4]
  d_model: [256, 512]
finrl_ppo:
  gamma: [0.9, 0.99]
  lr: [1e-5, 3e-4]
  n_steps: [128, 2048]
