linear_regression:
  fit_intercept: [true, false]
  normalize: [true, false]
random_forest:
  n_estimators: [100, 200, 300]
  max_depth: [null, 10, 20]
  min_samples_split: [2, 5, 10]
xgboost:
  n_estimators: [100, 200, 300]
  learning_rate: [0.01, 0.1, 0.2]
  max_depth: [3, 6, 9]
lightgbm:
  num_leaves: [31, 64, 128]
  learning_rate: [0.01, 0.1]
  n_estimators: [100, 200, 500]
catboost:
  depth: [6, 8, 10]
  learning_rate: [0.01, 0.05, 0.1]
  iterations: [300, 500, 700]
pytorch_lightning:
  lr: [0.001, 0.0001]
  batch_size: [32, 64, 128]
