lightgbm:
  num_leaves: [31, 64]
  learning_rate: [0.01, 0.1]
  n_estimators: [100, 200]
catboost:
  depth: [6, 8]
  learning_rate: [0.01, 0.05]
  iterations: [100, 200]
tabnet:
  lr: [0.01]
  epochs: [5]
prophet:
  changepoint_prior_scale: [0.01]
  seasonality_prior_scale: [5.0]
lstm:
  lr: [0.001]
  hidden: [16]
  epochs: [3]
tft:
  lr: [0.001]
  hidden: [32]
  epochs: [3]
autoformer:
  lr: [0.001]
  d_model: [32]
  epochs: [3]
informer:
  lr: [0.001]
  d_model: [32]
  epochs: [3]
patchtst:
  lr: [0.001]
  hidden: [32]
  epochs: [3]
timesnet:
  lr: [0.001]
  d_model: [32]
  epochs: [3]
finrl_ppo:
  lr: [0.0003]
  n_steps: [128]
