name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Remove macOS artifacts
        run: bash scripts/remove_macos_artifacts.sh
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install pandas numpy scikit-learn optuna mlflow prefect stable-baselines3 gymnasium
      - run: pytest -q
