name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install ruff
      - run: ruff check .

  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: Remove macOS artifacts
        run: bash scripts/remove_macos_artifacts.sh
        shell: bash
      - uses: actions/setup-node@v4
        with:
          node-version: 18
      - run: npm ci
      - run: npm run lint
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - run: pip install pandas numpy scikit-learn optuna mlflow prefect stable-baselines3 gymnasium pytest pytest-cov
      - run: pytest --cov=python --cov-report=xml -q
      - uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.os }}
          path: coverage.xml
